services:
  app:
    container_name: fantastic_spoon_tg
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
      - /root/dev/koishi-meme/public/meme:/memes
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - NODE_ENV=development
    restart: unless-stopped
